-- INSERIR EMPRESA
USE SGA;
SELECT * FROM EMPRESA;

INSERT INTO EMPRESA (NOME_EMPRESA, CNPJ_EMPRESA, INSCRICAO_MUNICIPAL, LICENSA)
	VALUES('EMPRESA TESTE', '123456789-0001', 'ISENTO', '778899');

    
-- INSERIR CONTRATO - DATA TEM QUE SER NO PADRAO AMERICANO AAAA-MM-DD

SELECT * FROM CONTRATO;

INSERT INTO CONTRATO (DATA_CONTRATO, DATA_VENCIMENTO_CONTRATO, EMPRESA_ID_EMPRESA) 
	VALUES('2018-05-06', '2019-05-06', 1);


    
-- INSERIR DOCUMENTO

SELECT * FROM DOCUMENTO;

INSERT INTO DOCUMENTO (TIPO_DOCUMENTO, NOME_DOCUMENTO, URL, CONTRATO_ID_CONTRATO)
	VALUES('CONTRATO', 'CONTRATO DESCARTE EMPRESA TESTE', 'DOCUMENTOS/CONTRATO', 1);
    
    
-- INSERIR RISCO BIOLOGICO

SELECT * FROM RISCO_BIOLOGICO;

INSERT INTO RISCO_BIOLOGICO (DESCRICAO_RISCO, GRAU_CONTAMINACAO)
	VALUES('CONTAMINAÇÃO DO SOLO POR METAL PESADO', 'GRAU 5');

INSERT INTO RISCO_BIOLOGICO (DESCRICAO_RISCO, GRAU_CONTAMINACAO)
	VALUES('CONTAMINAÇÃO DO LENÇOL FREATICO POR RADIACAO', 'GRAU 4');
    
-- INSERIR MATERIAL

SELECT * FROM MATERIAL;

INSERT INTO MATERIAL (NOME_MATERIAL, TIPO_MATERIAL)
	VALUES('PILHA ALCALINA', 'METAL');
    
INSERT INTO MATERIAL (NOME_MATERIAL, TIPO_MATERIAL)
	VALUES('ÓLEO VEICULAR', 'ÓLEO');
    
-- INSERIR UNIDADE MEDIDA

SELECT * FROM UNIDADE_MEDIDA;

INSERT INTO UNIDADE_MEDIDA (DESCRICAO)
 VALUES('KILO');
 
INSERT INTO UNIDADE_MEDIDA (DESCRICAO)
 VALUES('LITRO');
 
 -- INSERIR RELAÇÃO DE MATERIAL COM RISCO BIOLOGICO
 
SELECT * FROM RISCO_MATERIAL;
 
INSERT INTO RISCO_MATERIAL (MATERIAL_CODIGO_MATERIAL, RISCO_BIOLOGICO_ID_RISCO_BIOLOGICO) -- INSERINDO RISCO BIOLOGICO DA PILHA
	VALUES(1, 1);
 
INSERT INTO RISCO_MATERIAL (MATERIAL_CODIGO_MATERIAL, RISCO_BIOLOGICO_ID_RISCO_BIOLOGICO) -- INSERINDO RISCO BIOLOGICO DO ÓLEO
	VALUES(2, 2);
    
-- INSERIR LISTA DE MATERIAIS

SELECT * FROM LISTA_MATERIAL;

INSERT INTO LISTA_MATERIAL(PERIODO_GERACAO_INICIO, PERIODO_GERACAO_FIM)
	VALUES('2018-04-01', '2018-04-30');
    
-- INSERIR ITEM DA LISTA

SELECT * FROM ITEM_LISTA;

INSERT INTO ITEM_LISTA (QUANTIDADE_ITEM, UNIDADE_MEDIDA_ID_UNIDADE_MEDIDA, LISTA_MATERIAL_ID_LISTA_MATERIAL, MATERIAL_CODIGO_MATERIAL) -- INSERINDO PILHA
	VALUES('20', 1, 1, 1);
INSERT INTO ITEM_LISTA (QUANTIDADE_ITEM, UNIDADE_MEDIDA_ID_UNIDADE_MEDIDA, LISTA_MATERIAL_ID_LISTA_MATERIAL, MATERIAL_CODIGO_MATERIAL) -- INSERINDO OLEO
	VALUES('1000', 2, 1, 2);

-- INSERIR DOCUMENTO DE DESCARTE

SELECT * FROM DOCUMENTO;

INSERT INTO DOCUMENTO (TIPO_DOCUMENTO, NOME_DOCUMENTO, URL, CONTRATO_ID_CONTRATO)
	VALUES('ORDEM DE DESCARTE', 'DESCARTE REFERENTE AOS MATERIAIS POLUENTES PRODUZIDOS NO MÊS DE ABRIL', 'DOCUMENTOS/DESCARTES', 1);
    
/* UPDATE DOCUMENTO
	SET NOME_DOCUMENTO = 'DESCARTE REFERENTE AOS MATERIAIS POLUENTES PRODUZIDOS NO MÊS DE ABRIL'
    WHERE ID_DOCUMENTO = 2;
    
DELETE FROM DOCUMENTO
	WHERE ID_DOCUMENTO IN(2, 4);

   */ 
-- REALIZAR UM DESCARTE

SELECT * FROM DESCARTE_MATERIAL;

INSERT INTO DESCARTE_MATERIAL (DATA_DESCARTE, LOCAL_DESCARTE, DATA_COLETA, VALOR_TRANSACAO, LISTA_MATERIAL_ID_LISTA_MATERIAL, EMPRESA_ID_EMPRESA)
	VALUES('2018-05-12', 'ATERRO GRANJA VIANA', '2018-05-11', 1500.00, 1, 1);
    
    INSERT INTO DESCARTE_MATERIAL (DATA_DESCARTE, LOCAL_DESCARTE, DATA_COLETA, VALOR_TRANSACAO, LISTA_MATERIAL_ID_LISTA_MATERIAL, EMPRESA_ID_EMPRESA)
	VALUES('2018-05-25', 'ATERRO TABOAO DA SERRA', '2018-05-24', 700.00, 1, 1);

/*    
UPDATE descarte_material
	SET VALOR_TRANSACAO = '1500.00'
    WHERE ID_DESCARTE_MATERIAL = 1;

  */  
-- INSERIR RELACIONAMENTO DO DOCUMENTO AO DESCARTE

SELECT * FROM ITEM_DOCUMENTO_DESCARTE;

INSERT INTO ITEM_DOCUMENTO_DESCARTE (DOCUMENTO_ID_DOCUMENTO, 
                                     DESCARTE_MATERIAL_ID_DESCARTE_MATERIAL)
	VALUE(2, 1);
    
 --  ----------------------------------------------------
 
SELECT B.NOME_EMPRESA, 
	J.NOME_DOCUMENTO,
	A.DATA_COLETA, 
    A.VALOR_TRANSACAO, 
    E.NOME_MATERIAL,
    L.NOME_DOCUMENTO,
	D.QUANTIDADE_ITEM,
    H.DESCRICAO ,
    G.DESCRICAO_RISCO, 
    G.GRAU_CONTAMINACAO FROM descarte_material A
INNER JOIN EMPRESA B ON B.ID_EMPRESA = A.EMPRESA_ID_EMPRESA 
INNER JOIN LISTA_MATERIAL C ON C.ID_LISTA_MATERIAL = A.LISTA_MATERIAL_ID_LISTA_MATERIAL
INNER JOIN ITEM_LISTA D ON D.LISTA_MATERIAL_ID_LISTA_MATERIAL = C.ID_LISTA_MATERIAL
INNER JOIN MATERIAL E ON D.MATERIAL_CODIGO_MATERIAL = E.CODIGO_MATERIAL
INNER JOIN RISCO_MATERIAL F ON E.CODIGO_MATERIAL= F.MATERIAL_CODIGO_MATERIAL
INNER JOIN RISCO_BIOLOGICO G ON F.RISCO_BIOLOGICO_ID_RISCO_BIOLOGICO = G.ID_RISCO_BIOLOGICO
INNER JOIN UNIDADE_MEDIDA H ON D.UNIDADE_MEDIDA_ID_UNIDADE_MEDIDA = H.ID_UNIDADE_MEDIDA
INNER JOIN CONTRATO I ON B.ID_EMPRESA = I.EMPRESA_ID_EMPRESA
INNER JOIN DOCUMENTO J ON I.ID_CONTRATO = J.CONTRATO_ID_CONTRATO
INNER JOIN ITEM_DOCUMENTO_DESCARTE K ON A.ID_DESCARTE_MATERIAL = K.DESCARTE_MATERIAL_ID_DESCARTE_MATERIAL
INNER JOIN DOCUMENTO L ON L.ID_DOCUMENTO = K.DOCUMENTO_ID_DOCUMENTO
	WHERE A.DATA_COLETA between '2018-05-01' AND '2018-05-31';
